In [2]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup as BS
from IPython.core.display import HTML
from datetime import datetime, timedelta

In [260]:
week_ending_str = '2022-06-05'
week_ending = datetime.strptime(week_ending_str, '%Y-%m-%d')
modifier = timedelta(7)

show = []
weekblah = []
diff = []
avg = []
seats = []
perfs = []
cap = []
capdiff = []
week = []
i=1
week = []
while i in range(1,3):
    print(i)
    print(week_ending)
    #week.append(week_ending)                                                         #week
    
    url = f'https://www.playbill.com/grosses?week={str(week_ending.date())}'
    print(url)
    #response = requests.get(url)
    data = requests.get(url).text
    soup = BS(data, 'html.parser')
    table = soup.find('table', class_='bsp-table')
    #df = pd.DataFrame(columns=['Show', 'This Week Gross', 'Diff $', 'Avg Ticket', 'Seats Sold', 'Perfs', '% Cap', 'Diff % cap'])

    for row in table.tbody.find_all('tr'):    
        # Find all data for each column
        columns = row.find_all('td')
        if(columns != []):
            Show = columns[0].text.strip()
            show.append(Show)
            Week = columns[1].text.strip()
            weekblah.append(Week)
            Diff = columns[2].text.strip()
            diff.append(Diff)
            AvgTicket = columns[3].text.strip()
            avg.append(AvgTicket)
            Seats = columns[4].text.strip()
            seats.append(Seats)
            Perfs = columns[5].text.strip()
            perfs.append(Perfs)
            CapPerc = columns[6].text.strip()
            cap.append(CapPerc)
            CapPercDiff = columns[7].text.strip()
            capdiff.append(CapPercDiff)
            week.append(week_ending)

        #df = df.append({'Show': Show,  'This Week Gross': Week, 'Diff $': Diff, 'Avg Ticket': AvgTicket, 'Seats Sold': Seats, 'Perfs': Perfs, '% Cap': CapPerc, 'Diff % cap': CapPercDiff}, ignore_index=True)

    i +=1
    week_ending = week_ending - modifier 
df = pd.DataFrame({'Show': show,  'This Week Gross': weekblah, 'Diff $': diff, 'Avg Ticket': avg, 'Seats Sold': seats, 'Perfs': perfs, '% Cap': cap, 'Diff % cap': capdiff, 'Week': week,})
df[['Show','Theater']] = df['Show'].str.split('\n\n', expand=True)
#df[['This Week Gross', 'Potential Gross']] = df['This Week Gross'].str.split('\n', expand=True)
df[['Avg Ticket', 'Top Ticket']] = df['Avg Ticket'].str.split('\n', expand=True)
df[['Seats Sold', 'Seats in Theater']] = df['Seats Sold'].str.split('\n', expand=True)
df[['Perfs', 'Previews']] = df['Perfs'].str.split('\n', expand=True)

1
2022-06-05 00:00:00
https://www.playbill.com/grosses?week=2022-06-05
2
2022-05-29 00:00:00
https://www.playbill.com/grosses?week=2022-05-29

In [261]:
df

,Show,This Week Gross,Diff $,Avg Ticket,Seats Sold,Perfs,% Cap,Diff % cap,Week,Theater,Top Ticket,Seats in Theater,Previews
0,A Strange Loop,"$685,772.13",$0.00,$105.18,"6,520",8,89.36%,0.00%,2022-06-05,Lyceum Theatre,$347.00,912,0
1,Aladdin,"$1,188,639.17",$0.00,$90.00,"13,207",8,95.59%,0.00%,2022-06-05,New Amsterdam Theatre,$199.50,"1,727",0
2,American Buffalo,"$433,548.80",$0.00,$98.24,"4,413",8,73.45%,0.00%,2022-06-05,Circle in the Square Theatre,$299.50,751,0
3,Beetlejuice,"$1,019,501.50",$0.00,$114.63,"8,894",8,69.40%,0.00%,2022-06-05,Marquis Theatre,$249.00,"1,602",0
4,Chicago,"$763,452.49",$0.00,$97.90,"7,798",8,90.25%,0.00%,2022-06-05,Ambassador Theatre,$207.00,"1,080",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,The Phantom of the Opera,"$976,104.43",$0.00,$97.13,"10,049",8,78.26%,0.00%,2022-05-29,Majestic Theatre,$247.00,"1,605",0
62,The Skin of Our Teeth,"$289,682.00",$0.00,$51.49,"5,626",8,66.47%,0.00%,2022-05-29,Vivian Beaumont Theater,$225.00,"1,058",0
63,Tina: The Tina Turner Musical,"$909,005.50",$0.00,$117.20,"7,756",8,65.60%,0.00%,2022-05-29,Lunt-Fontanne Theatre,$249.00,"1,478",0
64,Wicked,"$1,780,207.00",$0.00,$130.30,"13,662",8,94.51%,0.00%,2022-05-29,Gershwin Theatre,$260.00,"1,807",0
65,for colored girls who have considered suicide/...,"$226,306.70",$0.00,$70.06,"3,230",8,52.23%,0.00%,2022-05-29,Booth Theatre,$223.00,773,0

In [246]:
df

,Show,This Week Gross,Diff $,Avg Ticket,Seats Sold,Perfs,% Cap,Diff % cap,Week,Theater,Potential Gross,Top Ticket,Seats in Theater,Previews
0,A Soldier's Play,"$529,469.00",$0.00,$90.85,"5,828",8,101.04%,0.00%,2022-04-10,American Airlines Theatre,"$655,256.00",$297.00,721,0
1,Ain't Too Proud—The Life and Times of the Temp...,"$920,904.24",$0.00,$100.54,"9,160",8,80.41%,0.00%,2022-04-10,Imperial Theatre,"$1,520,824.00",$297.00,"1,424",0
2,Aladdin,"$1,002,597.40",$0.00,$80.39,"12,471",8,90.26%,0.00%,2022-04-10,New Amsterdam Theatre,"$1,392,854.00",$227.50,"1,727",0
3,Beetlejuice,"$1,023,779.60",$0.00,$94.78,"10,802",8,90.44%,0.00%,2022-04-10,Winter Garden Theatre,"$1,310,008.00",$323.00,"1,493",0
4,Chicago,"$536,990.80",$0.00,$83.07,"6,464",8,74.81%,0.00%,2022-04-10,Ambassador Theatre,"$960,444.00",$197.00,"1,080",0
5,Come From Away,"$797,780.70",$0.00,$95.79,"8,328",8,99.52%,0.00%,2022-04-10,Gerald Schoenfeld Theatre,"$1,108,592.00",$297.00,"1,046",0
6,Company,"$779,588.10",$0.00,$124.16,"6,279",0,101.60%,0.00%,2022-04-10,Bernard B. Jacobs Theatre,"$875,460.00",$327.00,"1,030",6
7,Dear Evan Hansen,"$981,271.30",$0.00,$126.62,"7,750",8,98.45%,0.00%,2022-04-10,Music Box Theatre,"$1,234,034.00",$297.00,984,0
8,Frozen,"$798,610.40",$0.00,$73.48,"10,869",8,80.68%,0.00%,2022-04-10,St. James Theatre,"$1,156,856.00",$217.50,"1,684",0
9,Girl From the North Country,"$477,388.20",$0.00,$75.57,"6,317",4,79.12%,0.00%,2022-04-10,Belasco Theatre,"$939,738.00",$247.00,998,4
10,Hadestown,"$1,086,477.75",$0.00,$147.10,"7,386",8,100.57%,0.00%,2022-04-10,Walter Kerr Theatre,"$1,094,012.00",$0.00,918,0
11,Hamilton,"$2,688,721.00",$0.00,$250.07,"10,752",8,101.51%,0.00%,2022-04-10,Richard Rodgers Theatre,"$2,605,608.00",$847.00,"1,324",0
12,Hangmen,"$357,100.00",$0.00,$76.27,"4,682",0,83.40%,0.00%,2022-04-10,John Golden Theatre,"$743,418.00",$223.00,802,7
13,Harry Potter and the Cursed Child,"$994,703.00",$0.00,$77.80,"12,785",8,98.53%,0.00%,2022-04-10,Lyric Theatre,"$1,098,770.50",$296.50,"1,622",0
14,Jagged Little Pill,"$801,670.65",$0.00,$95.65,"8,381",8,93.12%,0.00%,2022-04-10,Broadhurst Theatre,"$1,241,400.00",$247.00,"1,125",0
15,Mean Girls,"$775,193.45",$0.00,$90.33,"8,582",8,87.57%,0.00%,2022-04-10,August Wilson Theatre,"$1,176,000.00",$249.50,"1,225",0
16,Moulin Rouge! The Musical,"$1,514,716.50",$0.00,$147.92,"10,240",8,98.31%,0.00%,2022-04-10,Al Hirschfeld Theatre,"$1,754,340.00",$399.00,"1,302",0
17,SIX: The Musical,"$884,878.20",$0.00,$108.79,"8,134",0,98.62%,0.00%,2022-04-10,Brooks Atkinson Theatre,"$1,057,206.00",$297.00,"1,031",8
18,The Book of Mormon,"$929,168.30",$0.00,$112.67,"8,247",8,98.46%,0.00%,2022-04-10,Eugene O'Neill Theatre,"$1,190,502.00",$477.50,"1,047",0
19,The Inheritance,"$430,156.50",$0.00,$73.81,"5,828",8,69.51%,0.00%,2022-04-10,Ethel Barrymore Theatre,"$1,137,638.00",$297.00,"1,048",0
20,The Lehman Trilogy,"$188,126.00",$0.00,$163.02,"1,154",0,100.00%,0.00%,2022-04-10,Nederlander Theatre,"$171,298.00",$397.00,"1,154",1
21,The Lion King,"$1,186,505.00",$0.00,$99.05,"11,979",8,88.29%,0.00%,2022-04-10,Minskoff Theatre,"$2,212,053.00",$237.00,"1,696",0
22,The Minutes,"$419,765.10",$0.00,$73.27,"5,729",0,66.99%,0.00%,2022-04-10,Studio 54,"$987,144.00",$267.00,"1,069",8
23,The Phantom of the Opera,"$652,565.00",$0.00,$74.95,"8,707",8,67.81%,0.00%,2022-04-10,Majestic Theatre,"$1,358,986.00",$213.00,"1,605",0
24,Tina: The Tina Turner Musical,"$1,225,999.00",$0.00,$129.68,"9,454",8,79.96%,0.00%,2022-04-10,Lunt-Fontanne Theatre,"$1,566,688.00",$297.00,"1,478",0
25,To Kill A Mockingbird,"$1,237,497.00",$0.00,$118.06,"10,482",8,91.31%,0.00%,2022-04-10,Sam S. Shubert Theatre,"$1,751,250.00",$423.00,"1,435",0
26,West Side Story,"$1,503,738.44",$0.00,$108.03,"13,920",8,100.00%,0.00%,2022-04-10,Broadway Theatre,"$1,722,464.00",$373.00,"1,740",0
27,Who's Afraid of Virginia Woolf?,"$344,817.50",$0.00,$79.93,"4,314",0,93.86%,0.00%,2022-04-10,Booth Theatre,"$649,692.00",$273.00,766,6
28,Wicked,"$1,254,306.00",$0.00,$96.63,"12,981",8,89.80%,0.00%,2022-04-10,Gershwin Theatre,"$1,779,845.00",$250.00,"1,807",0
29,A Soldier's Play,"$529,469.00",$0.00,$90.85,"5,828",8,101.04%,0.00%,2022-04-03,American Airlines Theatre,"$655,256.00",$297.00,721,0
30,Ain't Too Proud—The Life and Times of the Temp...,"$920,904.24",$0.00,$100.54,"9,160",8,80.41%,0.00%,2022-04-03,Imperial Theatre,"$1,520,824.00",$297.00,"1,424",0
31,Aladdin,"$1,002,597.40",$0.00,$80.39,"12,471",8,90.26%,0.00%,2022-04-03,New Amsterdam Theatre,"$1,392,854.00",$227.50,"1,727",0
32,Beetlejuice,"$1,023,779.60",$0.00,$94.78,"10,802",8,90.44%,0.00%,2022-04-03,Winter Garden Theatre,"$1,310,008.00",$323.00,"1,493",0
33,Chicago,"$536,990.80",$0.00,$83.07,"6,464",8,74.81%,0.00%,2022-04-03,Ambassador Theatre,"$960,444.00",$197.00,"1,080",0
34,Come From Away,"$797,780.70",$0.00,$95.79,"8,328",8,99.52%,0.00%,2022-04-03,Gerald Schoenfeld Theatre,"$1,108,592.00",$297.00,"1,046",0
35,Company,"$779,588.10",$0.00,$124.16,"6,279",0,101.60%,0.00%,2022-04-03,Bernard B. Jacobs Theatre,"$875,460.00",$327.00,"1,030",6
36,Dear Evan Hansen,"$981,271.30",$0.00,$126.62,"7,750",8,98.45%,0.00%,2022-04-03,Music Box Theatre,"$1,234,034.00",$297.00,984,0
37,Frozen,"$798,610.40",$0.00,$73.48,"10,869",8,80.68%,0.00%,2022-04-03,St. James Theatre,"$1,156,856.00",$217.50,"1,684",0
38,Girl From the North Country,"$477,388.20",$0.00,$75.57,"6,317",4,79.12%,0.00%,2022-04-03,Belasco Theatre,"$939,738.00",$247.00,998,4
39,Hadestown,"$1,086,477.75",$0.00,$147.10,"7,386",8,100.57%,0.00%,2022-04-03,Walter Kerr Theatre,"$1,094,012.00",$0.00,918,0
40,Hamilton,"$2,688,721.00",$0.00,$250.07,"10,752",8,101.51%,0.00%,2022-04-03,Richard Rodgers Theatre,"$2,605,608.00",$847.00,"1,324",0
41,Hangmen,"$357,100.00",$0.00,$76.27,"4,682",0,83.40%,0.00%,2022-04-03,John Golden Theatre,"$743,418.00",$223.00,802,7
42,Harry Potter and the Cursed Child,"$994,703.00",$0.00,$77.80,"12,785",8,98.53%,0.00%,2022-04-03,Lyric Theatre,"$1,098,770.50",$296.50,"1,622",0
43,Jagged Little Pill,"$801,670.65",$0.00,$95.65,"8,381",8,93.12%,0.00%,2022-04-03,Broadhurst Theatre,"$1,241,400.00",$247.00,"1,125",0
44,Mean Girls,"$775,193.45",$0.00,$90.33,"8,582",8,87.57%,0.00%,2022-04-03,August Wilson Theatre,"$1,176,000.00",$249.50,"1,225",0
45,Moulin Rouge! The Musical,"$1,514,716.50",$0.00,$147.92,"10,240",8,98.31%,0.00%,2022-04-03,Al Hirschfeld Theatre,"$1,754,340.00",$399.00,"1,302",0
46,SIX: The Musical,"$884,878.20",$0.00,$108.79,"8,134",0,98.62%,0.00%,2022-04-03,Brooks Atkinson Theatre,"$1,057,206.00",$297.00,"1,031",8
47,The Book of Mormon,"$929,168.30",$0.00,$112.67,"8,247",8,98.46%,0.00%,2022-04-03,Eugene O'Neill Theatre,"$1,190,502.00",$477.50,"1,047",0
48,The Inheritance,"$430,156.50",$0.00,$73.81,"5,828",8,69.51%,0.00%,2022-04-03,Ethel Barrymore Theatre,"$1,137,638.00",$297.00,"1,048",0
49,The Lehman Trilogy,"$188,126.00",$0.00,$163.02,"1,154",0,100.00%,0.00%,2022-04-03,Nederlander Theatre,"$171,298.00",$397.00,"1,154",1
50,The Lion King,"$1,186,505.00",$0.00,$99.05,"11,979",8,88.29%,0.00%,2022-04-03,Minskoff Theatre,"$2,212,053.00",$237.00,"1,696",0
51,The Minutes,"$419,765.10",$0.00,$73.27,"5,729",0,66.99%,0.00%,2022-04-03,Studio 54,"$987,144.00",$267.00,"1,069",8
52,The Phantom of the Opera,"$652,565.00",$0.00,$74.95,"8,707",8,67.81%,0.00%,2022-04-03,Majestic Theatre,"$1,358,986.00",$213.00,"1,605",0
53,Tina: The Tina Turner Musical,"$1,225,999.00",$0.00,$129.68,"9,454",8,79.96%,0.00%,2022-04-03,Lunt-Fontanne Theatre,"$1,566,688.00",$297.00,"1,478",0
54,To Kill A Mockingbird,"$1,237,497.00",$0.00,$118.06,"10,482",8,91.31%,0.00%,2022-04-03,Sam S. Shubert Theatre,"$1,751,250.00",$423.00,"1,435",0
55,West Side Story,"$1,503,738.44",$0.00,$108.03,"13,920",8,100.00%,0.00%,2022-04-03,Broadway Theatre,"$1,722,464.00",$373.00,"1,740",0
56,Who's Afraid of Virginia Woolf?,"$344,817.50",$0.00,$79.93,"4,314",0,93.86%,0.00%,2022-04-03,Booth Theatre,"$649,692.00",$273.00,766,6
57,Wicked,"$1,254,306.00",$0.00,$96.63,"12,981",8,89.80%,0.00%,2022-04-03,Gershwin Theatre,"$1,779,845.00",$250.00,"1,807",0